### ISSUE TITLE
Segfault when volume is higher than 100%

### ISSUE THREAD

**Issue by Nothing4You** [nicklan/pnmixer#27]
Hey there, when I adjust the volume to more than 100% pnmixer just segfaults:

`$ gdb`
```
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) file /usr/bin/pnmixer
Reading symbols from /usr/bin/pnmixer...done.
(gdb) run
Starting program: /usr/bin/pnmixer 
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Debugging Mode Build]
Opening mixer for card: default
[New Thread 0x7fffe61e0700 (LWP 11699)]
[Thread 0x7fffe61e0700 (LWP 11699) exited]
Channels for card: default
	Master
Opening mixer for card: hw:0
hw:0 has no playable channels
Opening mixer for card: hw:1
Channels for card: hw:1
	Master
	Headphone
	Speaker
	PCM
	Mic
	Mic Boost
	Beep
	Internal Mic Boost
Opening mixer for card: hw:29
hw:29 has no playable channels
Opening mixer for card: default
[New Thread 0x7fffe61e0700 (LWP 11700)]
[getvol] From mixer: 40304  pmin: 0  pmax: 65536
[getvol] From mixer: 40304  pmin: 0  pmax: 65536
[getvol] From mixer: 65536  pmin: 0  pmax: 65536
[getvol] From mixer: 65536  pmin: 0  pmax: 65536
[getvol] From mixer: 65536  pmin: 0  pmax: 65536
[New Thread 0x7fffe58cf700 (LWP 11708)]
[getvol] From mixer: 70148  pmin: 0  pmax: 65536
[getvol] From mixer: 70148  pmin: 0  pmax: 65536

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6def577 in g_slice_alloc () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff6def577 in g_slice_alloc () from /usr/lib/libglib-2.0.so.0
#1  0x00007ffff6dd0216 in g_list_prepend () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff70a034e in g_object_newv () from /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff70a0cd6 in g_object_new_valist () from /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff70a1044 in g_object_new () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff72e259c in gdk_pixbuf_new_from_data () from /usr/lib/libgdk_pixbuf-2.0.so.0
#6  0x00007ffff72e02c7 in gdk_pixbuf_new () from /usr/lib/libgdk_pixbuf-2.0.so.0
#7  0x00007ffff72e7712 in gdk_pixbuf_scale_simple () from /usr/lib/libgdk_pixbuf-2.0.so.0
#8  0x00007ffff7957ee6 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#9  0x00000000004078d7 in get_mute_state (set_check=1) at main.c:356
#10 0x0000000000408ede in alsa_cb (e=0x6cc100, mask=1) at alsa.c:139
#11 0x00007ffff6ae32b6 in ?? () from /usr/lib/libasound.so.2
#12 0x00007ffff6add4b3 in ?? () from /usr/lib/libasound.so.2
#13 0x00007ffff6ad33e7 in snd_hctl_handle_events () from /usr/lib/libasound.so.2
#14 0x00007ffff6ade541 in snd_mixer_handle_events () from /usr/lib/libasound.so.2
#15 0x0000000000408f51 in poll_cb (source=0x6ca3c0, condition=G_IO_IN, data=0x0) at alsa.c:155
#16 0x00007ffff6dd3f06 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#17 0x00007ffff6dd4258 in ?? () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff6dd465a in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#19 0x00007ffff78e08f7 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#20 0x0000000000408144 in main (argc=1, argv=0x7fffffffe798) at main.c:508
```

**Comment by hasufell** [comment]
Can anyone reproduce this?

**Comment by Nothing4You** [comment]
Unfortunately I don't have any machine running arch anymore for the time being.
