### ISSUE TITLE
Abort when pulseaudio is not available (like pa having crashed)

### ISSUE THREAD

**Issue by Nothing4You** [nicklan/pnmixer#28]
When pnmixer is running while it PA crashes it asks me to reinitialize the connection to alsa, if either then or already at startup PA isn't available this happens (PA is not running):
`$ gdb`
```
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) file /usr/bin/pnmixer
Reading symbols from /usr/bin/pnmixer...done.
(gdb) run
Starting program: /usr/bin/pnmixer 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Debugging Mode Build]
Opening mixer for card: default
[New Thread 0x7fffe61dc700 (LWP 13409)]
default has no playable channels
Opening mixer for card: hw:0
hw:0 has no playable channels
Opening mixer for card: hw:1
Channels for card: hw:1
	Master
	Headphone
	Speaker
	PCM
	Mic
	Mic Boost
	Beep
	Internal Mic Boost
Opening mixer for card: hw:29
[Thread 0x7fffe61dc700 (LWP 13409) exited]
hw:29 has no playable channels
Opening mixer for card: default
[New Thread 0x7fffe61dc700 (LWP 13410)]
pnmixer: alsa.c:273: alsaset: Assertion `elem != ((void *)0)' failed.
[Thread 0x7fffe61dc700 (LWP 13410) exited]

Program received signal SIGABRT, Aborted.
0x00007ffff5cbe1c9 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5cbe1c9 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff5cbf5c8 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff5cb7356 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff5cb7402 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000000000409446 in alsaset () at alsa.c:273
#5  0x0000000000409869 in alsa_init () at alsa.c:368
#6  0x0000000000408061 in main (argc=1, argv=0x7fffffffe798) at main.c:496
```

**Comment by landroni** [comment]
Is this still valid? I'm always running pnmixer without PA, and no crashes here...

**Comment by hasufell** [comment]
we don't know, as we don't support PA
